### ISSUE TITLE
soul impact cooldown reduction in Feast of Dammned upgrade is buggy

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#289]
KRPower.m#638
I think it should use the remaining time instead of the old progressCircle->getDuration(). 

Mmlh says not to fix it because it will be a big nerf.

**Comment by Mmlh1** [comment]
The main issue that makes fixing it hard is Lozagon iron (stage 14 iron). It heavily relies on the spell basically instantaneously coming back, so without a redesign of this level, it's really hard to fix the Feast bug.

**Comment by Mmlh1** [comment]
Also 23 iron somewhat depends on it. Cigumo also mentioned that after each reduction, it casts the cooldown to an integer, so you often get back almost 3 seconds rather than 2 seconds. Furthermore, kills from the spectres that Soul Impact gets do not count, which makes it very luck dependent whether or not kills give you a cooldown reduction.
