### ISSUE TITLE
Towers sometimes randomly stop attacking

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#305]
https://www.youtube.com/watch?v=FM4E_2twijw

This, but without being frozen again, it lasts forever, and it can also happen without Svell Druids being involved. I have had it happen on Maginicia Shores, for example.

**Comment by Mmlh1** [comment]
Same as #265

**Comment by pablorealini** [comment]
Is there a way to easy reproduce this? probably not.

**Comment by Mmlh1** [comment]
Not that I know of.

Here is another video where the tower bugs out in another way (this is a much older version ofc)
https://youtu.be/a8-o2mX90_0?t=183

**Comment by pablorealini** [comment]
ok, but....this bug is only with goblirangs?

**Comment by pablorealini** [comment]
> Not that I know of.
> 
> Here is another video where the tower bugs out in another way (this is a much older version ofc) https://youtu.be/a8-o2mX90_0?t=183

Ok, I already found this one.

**Comment by Mmlh1** [comment]
Not only with Goblirangs, I just happen to only have recorded examples of them but I have seen it happen to Rocket Riders as well for example and other towers.

**Comment by pablorealini** [comment]
Ok, but these 2 issues: 
- https://youtu.be/a8-o2mX90_0?t=183
- https://www.youtube.com/watch?v=FM4E_2twijw
are specific for goblirangs, the bug is not in the tower block modifier. 
I manage to reproduce the bug and this is occurring because of a bad implementation in the cancel of the skill named **Biggarangs**

If you manage to find the towers please create specific issues for them..I will check Rocket riders also.

**Comment by Mmlh1** [comment]
Ah okay, I will see if I find it on other towers!

**Comment by pablorealini** [comment]
Ok, this 2 bugs are fixed, will be in the next update.
