### ISSUE TITLE
Shaolin Temple is not affected by GXR-1 Targeting System

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#370]
I think it should be since it's a ranged tower.

**Comment by gersonrpg** [comment]
It could or could not affect that tower, but it is more pro player if it extend Shaolin´s range.

So the upgrade should affect the tower

**Comment by pablorealini** [comment]
Ok, found 2 more bugs while fixing this.

1. The tower was attacking outside its range, mostly because it was configured to predict. This attack stuns almost instantaneously, so there is no need for prediction.
2. Also the center of the "range" was moved a little bit causing to have some kind of offset regarding the actual range from the ui.

Both bugs were like a buff to the tower....mostly the first one.
