### ISSUE TITLE
Sandworm tower targets flying enemies

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#389]
Sandworm Hollow's Snack Time ability seems to be able to target flying enemies, despite being unable to actually kill them. Should be changed so that they either can't target flying enemies, or can kill them. |   | TheGreenDigi | Nov 24 |   | Android 12
-- | -- | -- | -- | -- | --

**Comment by pablorealini** [comment]
Ok, this is what we will do here.
- It will not target flying units.
- But! it will try to eat them but using the HIT position and not the "anchor" position. This is mostly because if we use the shadow-anchor position it will look strange because the tremor is not tall enough to cover the flying units, and they will disappear. But using hit position for this will cause that if a unit is flying low it will eat them providing a pro-player experience.
