### ISSUE TITLE
Sandworm attacks during fade in/fade out increasing damage 1.5s

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#394]
This is a major issue because it affects a number of other similar skills (ex. Mortemis fumes or Ignis attack) and significantly increases their damage (Sandworm goes from an effective 280 per attack to 400)

**Comment by cigumo** [comment]
Sandworm seems to attack way longer than the 3.5 seconds that appear in the files. It seems to be around 5 seconds, making it inactive for only one second, approx. This is arguably because the attacks is extended during the start and end animations, making its damage output ridiculousliy high

**Comment by pablorealini** [comment]
Need more info, I don't understand the problem.
Every time we balance a skill we take into consideration the animations, etc etc

**Comment by Emicon97** [comment]
@pablorealini, like Cigumo mentioned, according to the tower plist file, the level 4 Sandworm is listed to attack during 3.5 seconds (the lower tiers are supposed to last less time), but instead, it attacks over 5 seconds approx. This translates into the tower dealing an insane amount of damage, even at lower tiers.

The issue might be related to the attack starting to take effect right at the start of the fade-in animation, and stopping to do so at the end of the fade-out animation. If this can't be mitigated, it would probably be a good idea to reduce the tower's cooldown a little bit.
![imagen](https://github.com/ironhidegames/issues-kr4/assets/94487044/78fee71b-8f7b-4d44-9ee6-e6175ef13861)

**Comment by pablorealini** [comment]
Okay, I understand, but we haven't informed the players that the attack takes 3.5 seconds. So, why are you assuming this is a bug rather than an intended feature? These files are for internal issues, so if there's a discrepancy between what you see in the file and what you experience in the game, it doesn't necessarily mean it's unintended. Perhaps the game designers considered the fade-in and fade-out timings.

I will check this with GD.

**Comment by Mmlh1** [comment]
Maybe this 'bonus duration' is intended, but its DPS is now roughly equal to a good archer or mage tower, but in a large area rather than single target. So that is why we are mentioning this - it feels like the DPS is higher than we would expect it to be.

**Comment by pablorealini** [comment]
Agree, maybe DPS is very high, we will for sure review that.
Also this object in the game **fx_loop_floor** can be configured to not apply the tick modifier during start animation, in this case the GD configured to apply that modifier.  `tick_on_start` `YES`
This object DO not apply the modifier during the end animation so is not 5s, I believe is 3.5s + start animation 0.866s duration 4.33 aprox in level 4.

**Comment by Mmlh1** [comment]
From testing, a single attack deals 20 ticks of damage exactly at level 4. I think it is 14/16/18/20 for levels 1-4 in that order.

**Comment by pablorealini** [comment]
The duration of the decal  ticks with a cooldown of 0.1s so:
Level1: 29 ticks. around 2.9s 
Level2: 34 ticks. around 3.4s
Level3: 38 ticks. around 3.8s
Level4: 44 ticks. around 4.4s

But then the modifier duration is 0.5s and ticks with a cooldown of 0.25s
We can asumen that if an enemy is stopped inside the aura during the whole duration:
Level1: 1 + 11 + 2 (14) more probably because the modifier duration add 2 more ticks
Level2: 1 + 13 + 2 (16)
Level3: 1 + 15 + 2  (18)
Level4: 1 + 17 + 2  (20)

I **debugged** and I can confirm this numbers, so you are correct.

**Comment by pablorealini** [comment]
Max damage when blocked inside the decal:

lvl1 - 56
lvl2 - 160
lvl3 - 270
lvl4 - 400

**Comment by Mmlh1** [comment]
I went with the very scientific method of modding level 1 dark knights to have 10x hp and 0 damage attack, and watching the enemy hp bars 😂

**Comment by gersonrpg** [comment]
In a previous revision, the cost was lowered by 10% and the stats were maintained. Maybe because it is already a tower with a lot of potential, this ends up generating a greater impact than it should. We lower its stats by 10% too. Anyway, it is an expensive and premium tower, so you should not forget that there is no level 4 ST tower of that accumulated cost, so it will clearly have more dmg capacity than the archer tower.
