### ISSUE TITLE
Defective Engines does not work

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#484]
It deals 0 damage. According to Mmlh, it's probably related to the new changes on the node explosions.

**Comment by Mmlh1** [comment]
I assumed that because it's the only related thing that was changed during the update. I could very well be wrong.

Edit: I was wrong. Anyway, enjoy this video from before the fix. It works like a charm after the fix, no worries.
https://cdn.discordapp.com/attachments/1243295563164684378/1284306984585138249/2024_09_14_02_14_34_trim.mp4?ex=66eac4d6&is=66e97356&hm=58425714892a3c791048827457c4fc6bc3dc8657cad40756b51a667efaa73f00&

**Comment by cigumo** [comment]
It's a bug. We'll fix it post-dlc release

**Comment by cigumo** [comment]
fixed in 1.16.1.2
